# default config.yml

#config version for us devs. DONT CHANGE THIS, or it will screw up some things PRETTY badly.
config:
  version: 1.3

######################################
######## Game Configuration ######### 
######################################

# The world(s) that all HA features are restricted to.
# If left blank all worlds will be allowed.
# ie:
# worlds:
# - world
# - world_nether
worlds:

# If left at 0 there will be no death match, fill in a time in minutes
DeathMatch: 0

#Whether or not to broadcast game messages to all players
broadcastAll: true

# The max amount of players that can be in a game, This is also dependent on the amount of startpoints you have set.
maxPlayers: 24

# Message to display when the games start
Start_Message: '&bLet The Games Begin!'

# If the games should automatically restart at the end
Auto_Restart: 'false'

# If it should automatically start the countdown on warping
Auto_Start: 'false'

# If tributes need to type /ha confirm to join
Need_Confirm: 'true'

# Whether or not the countdown will start upon warping.
Countdown: 'true'

# Duration of the countdown .
Countdown_Timer: 15

# How long the grace period should last (seconds)
Grace_Period: 60

# Whether or not players can break ANY blocks while playing
Protected_Arena: 'true'

# Whether or not players (not playing) can break blocks while waiting
Protected_Arena_Always: 'true'

# Whether new or unknown players on HA-maps should be forced to the spawn or not.
Force_Players_toSpawn: 'true'

# Whether or not players will be frozen when they are teleported to their positions
Frozen_Teleport: 'true'

# If the Tributes will get blown to bits when stepping off the pedestal
Explode_on_Move: 'false'

# Whether or not thunder will sound upon a players death
Cannon_Death: 'true'
######################################
######################################
######################################

################################
###### Rewards/Sponsoring ######
################################

# What the reward for winning is
Reward:
- 264,10
Sponsor_Cost:
- 264,1
EntryFee:
  enabled: false
  eco: false
  cost: 50
  fee:
  - 265,1
# True means give money to winner, false means don't.
rewardEco:
  enabled: false
  reward: 100
sponsorEco:
  enabled: false
  cost: 50
# How much money to give the winner.
# What sponsors have to pay to sponsor tributes
################################
################################
################################

#############################
####### Chat Related ########
#############################

# If players will only talk to close players of the whole server
ChatClose: 'true'

# How close the players have to be to talk to them
ChatClose_Radius: 10
#############################
#############################
#############################